// <auto-generated />
using System;
using DotnetYuzuncuYil.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotnetYuzuncuYil.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DotnetYuzuncuYil.Core.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BlogContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BlogCreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BlogImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("WriterID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryID");

                    b.HasIndex("WriterID");

                    b.ToTable("Blogs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BlogContent = "Yeni bir yıla girerken, 2023'ü büyük bir acı ile başlayıp 100. yıl coşkusuyla uğurladık. Türkiye Finans olarak, bu yıl boyunca yenilikçi yapımızın odağına insanı alarak değerli paydaşlarımızla birlikte yoğun bir yıl geçirdik.",
                            BlogCreateDate = new DateTime(2024, 1, 23, 0, 43, 52, 71, DateTimeKind.Local).AddTicks(7446),
                            BlogImage = "https://www.turkiyefinans.com.tr/tr-tr/blog/PublishingImages/2023-detay.jpg",
                            CategoryID = 2,
                            Name = "2023'ü Geride Bırakırken",
                            WriterID = 3
                        },
                        new
                        {
                            Id = 2,
                            BlogContent = "İyi görünen insanları diğerlerinden ayıran temel özelliklerden biri ince bir bele sahip olmalarıdır. İnce bir bel estetik açıdan göze daha hoş gelir. İnce olmak ve fit görünmek için çok çalışırız. Bel çevresinde biriken yağlardan tamamen kurtulamayız. Bu yağlardan kurtulmak istiyorsak bel bölgesini hedef alan bazı egzersizler vardır. Bel inceltmek için en hızlı hareketleri evde, hiçbir aparat kullanmadan uygulayabilirsiniz",
                            BlogCreateDate = new DateTime(2024, 1, 23, 0, 43, 52, 71, DateTimeKind.Local).AddTicks(7455),
                            BlogImage = "https://www.skechers.com.tr/blog/wp-content/uploads/2023/05/Bel-inceltme-Hareketleri.jpg",
                            CategoryID = 4,
                            Name = "Bel inceltme Hareketleri",
                            WriterID = 1
                        },
                        new
                        {
                            Id = 3,
                            BlogContent = "Kaplumbağa Terbiyecisi Tablosu, Osman Hamdi Bey tarafından 1906 ve 1907 yıllarında iki farklı çeşidini çizdiği resimlerdir.Osmanlı İmparatorluğu Lale Devri’ndeki “Sadabad Eğlenceleri” nde gece bahçelerin aydınlatılması için kaplumbağaların sırtlarına mumlar dikilerek serbest bırakılmaları bilgisi hikaye olarak anlatılır.\r\n\r\nO dönemde kaplumbağalar, dikkat çeken hizmetliler olarak görülür ve eğlencelere dahil edilirdi.",
                            BlogCreateDate = new DateTime(2024, 1, 23, 0, 43, 52, 71, DateTimeKind.Local).AddTicks(7456),
                            BlogImage = "https://www.lavitasarim.com/wp-content/uploads/2020/08/kaplumbaga-terbiyecisi-osman-hamdi-bey-lavi-tasarim.jpg",
                            CategoryID = 1,
                            Name = "Kaplumbağa Terbiyecisi Tablosu Hikayesi ve Anlamı",
                            WriterID = 2
                        });
                });

            modelBuilder.Entity("DotnetYuzuncuYil.Core.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CategoryDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CategoryStatus")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryStatus = true,
                            Name = "Sanat"
                        },
                        new
                        {
                            Id = 2,
                            CategoryStatus = true,
                            Name = "Ekonomi"
                        },
                        new
                        {
                            Id = 3,
                            CategoryStatus = true,
                            Name = "Edebiyat"
                        },
                        new
                        {
                            Id = 4,
                            CategoryStatus = true,
                            Name = "Spor"
                        });
                });

            modelBuilder.Entity("DotnetYuzuncuYil.Core.Models.Writer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Writers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "gokce_balci@gmail.com",
                            Name = "Gökçe",
                            Password = "1wfy54",
                            Surname = "Balcı",
                            UserName = "gokcebalci"
                        },
                        new
                        {
                            Id = 2,
                            Email = "akın_yılmaz@gmail.com",
                            Name = "Akın",
                            Password = "02ax5tp",
                            Surname = "Yılmaz",
                            UserName = "akinyilmaz"
                        },
                        new
                        {
                            Id = 3,
                            Email = "deniz_gokturk@gmail.com",
                            Name = "Deniz",
                            Password = "84dc774",
                            Surname = "Göktürk",
                            UserName = "denizgokturk"
                        });
                });

            modelBuilder.Entity("DotnetYuzuncuYil.Core.Models.Blog", b =>
                {
                    b.HasOne("DotnetYuzuncuYil.Core.Models.Category", "Category")
                        .WithMany("Blogs")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotnetYuzuncuYil.Core.Models.Writer", "Writer")
                        .WithMany("Blogs")
                        .HasForeignKey("WriterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Writer");
                });

            modelBuilder.Entity("DotnetYuzuncuYil.Core.Models.Category", b =>
                {
                    b.Navigation("Blogs");
                });

            modelBuilder.Entity("DotnetYuzuncuYil.Core.Models.Writer", b =>
                {
                    b.Navigation("Blogs");
                });
#pragma warning restore 612, 618
        }
    }
}
